; Minimal tree-sitter highlight query for Kotlin.

(line_comment) @comment
(multiline_comment) @comment

(string_literal) @string
(character_literal) @string

(integer_literal) @number
(real_literal) @number
(hex_literal) @number
(bin_literal) @number

"abstract" @keyword
"actual" @keyword
"annotation" @keyword
"as" @keyword
"break" @keyword
"by" @keyword
"catch" @keyword
"class" @keyword
"companion" @keyword
"const" @keyword
"constructor" @keyword
"continue" @keyword
"crossinline" @keyword
"data" @keyword
"do" @keyword
"dynamic" @keyword
"else" @keyword
"enum" @keyword
"expect" @keyword
"external" @keyword
"false" @keyword
"field" @keyword
"file" @keyword
"final" @keyword
"finally" @keyword
"for" @keyword
"fun" @keyword
"get" @keyword
"if" @keyword
"import" @keyword
"in" @keyword
"infix" @keyword
"init" @keyword
"inline" @keyword
"inner" @keyword
"interface" @keyword
"internal" @keyword
"is" @keyword
"lateinit" @keyword
"noinline" @keyword
"object" @keyword
"open" @keyword
"operator" @keyword
"out" @keyword
"override" @keyword
"package" @keyword
"private" @keyword
"protected" @keyword
"public" @keyword
"reified" @keyword
"return" @keyword
"sealed" @keyword
"set" @keyword
"super" @keyword
"suspend" @keyword
"tailrec" @keyword
"this" @keyword
"throw" @keyword
"true" @keyword
"try" @keyword
"typealias" @keyword
"val" @keyword
"var" @keyword
"vararg" @keyword
"when" @keyword
"where" @keyword
"while" @keyword

(simple_identifier) @variable
