; Zig syntax highlighting - one pattern per line so the truncate-on-error
; fallback in SyntaxManager can drop only the offending keyword instead
; of the entire bracketed list.

"const" @keyword
"var" @keyword
"fn" @keyword
"struct" @keyword
"union" @keyword
"enum" @keyword
"error" @keyword
"opaque" @keyword
"pub" @keyword
"export" @keyword
"extern" @keyword
"inline" @keyword
"noinline" @keyword
"comptime" @keyword
"async" @keyword
"nosuspend" @keyword
"await" @keyword
"resume" @keyword
"suspend" @keyword
"defer" @keyword
"errdefer" @keyword
"unreachable" @keyword
"try" @keyword
"catch" @keyword
"orelse" @keyword
"if" @keyword
"else" @keyword
"switch" @keyword
"while" @keyword
"for" @keyword
"break" @keyword
"continue" @keyword
"return" @keyword
"usingnamespace" @keyword
"test" @keyword
"and" @keyword
"or" @keyword
"asm" @keyword
"volatile" @keyword
"linksection" @keyword
"threadlocal" @keyword
"align" @keyword
"allowzero" @keyword
"callconv" @keyword
"anytype" @keyword
"anyframe" @keyword
"undefined" @keyword
"null" @keyword
"true" @keyword
"false" @keyword

"+" @operator
"-" @operator
"*" @operator
"/" @operator
"%" @operator
"++" @operator
"**" @operator
"<<" @operator
">>" @operator
"&" @operator
"|" @operator
"^" @operator
"~" @operator
"==" @operator
"!=" @operator
"<" @operator
">" @operator
"<=" @operator
">=" @operator
"!" @operator
"?" @operator
".?" @operator
".*" @operator
"&=" @operator
"|=" @operator
"^=" @operator
"+=" @operator
"-=" @operator
"*=" @operator
"/=" @operator
"%=" @operator
"<<=" @operator
">>=" @operator
"=" @operator
"=>" @operator
"->" @operator
".." @operator
"..." @operator
